##############################################################
# Build that shit.
##############################################################
build:
  stage: build
  image: microsoft/dotnet:latest
  except:
    - tags
  script:
    - dotnet restore
    - dotnet publish -c Release -r win-x86
    - dotnet publish -c Release -r win-x64
  artifacts:
    paths:
      - ./package

##############################################################
# Running unit tests.
##############################################################
test/unit-testing:
  stage: test
  image: microsoft/dotnet:latest
  except:
    - tags
  script:
    - dotnet test

##############################################################
# Deployment.
##############################################################
deploy/nuget:
  stage: deploy
  image: microsoft/dotnet:latest
  only:
    - master
  except:
    - tags
  script:
    dotnet nuget push ./package/*.nupkg -k $NUGET_API_KEY -s nuget.org
