##############################################################
# Build that shit.
##############################################################
build:
  stage: build
  image: mcr.microsoft.com/dotnet/framework/sdk:4.8
  except:
    - tags
  script:
    - dotnet restore
    - msbuild . /t:Build /p:Configuration=Release /p:TargetFramework=v4.7
  artifacts:
    paths:
      - ./kOS.Cli/bin/Release

##############################################################
# Running unit tests.
##############################################################
# test/unit-testing:
#   stage: test
#   image: mcr.microsoft.com/dotnet/framework/sdk:4.8
#   except:
#     - tags
#   script:
#     - dotnet test

##############################################################
# Deployment.
##############################################################
# deploy/nuget:
#   stage: deploy
#   image: microsoft/dotnet:latest
#   only:
#     - master
#   except:
#     - tags
#   script:
#     dotnet nuget push ./package/*.nupkg -k $NUGET_API_KEY -s nuget.org