##############################################################
# Build that shit.
##############################################################
build/debug:
  stage: build
  image: microsoft/dotnet:latest
  only:
    - develop
  except:
    - tags
  before_script:
    - ./ci-cd/upgrade-to-4.7.2.sh
  script:
    - dotnet restore
    - dotnet build

build/x64:
  stage: build
  image: microsoft/dotnet:latest
  only:
    - master
  except:
    - tags
  before_script:
    - ./ci-cd/upgrade-to-4.7.2.sh
  script:
    - dotnet restore
    - dotnet tool install --global dotnet-warp
    - cd ./kOS.Cli
    - dotnet-warp -r win-x64 -o ../win-x64/ksc.exe
  artifacts:
    paths:
      - ./win-x64/ksc.exe

build/x86:
  stage: build
  image: microsoft/dotnet:latest
  only:
    - master
  except:
    - tags
  before_script:
    - ./ci-cd/upgrade-to-4.7.2.sh
  script:
    - dotnet restore
    - dotnet tool install --global dotnet-warp
    - cd ./kOS.Cli
    - dotnet-warp -r win-x86 -o ../win-x86/ksc.exe
  artifacts:
    paths:
      - ./win-x86/ksc.exe

build/linux-x64:
  stage: build
  image: microsoft/dotnet:latest
  only:
    - master
  except:
    - tags
  before_script:
    - ./ci-cd/upgrade-to-4.7.2.sh
  script:
    - dotnet restore
    - dotnet tool install --global dotnet-warp
    - cd ./kOS.Cli
    - dotnet-warp -r linux-x64 -o ../linux-x64/ksc
  artifacts:
    paths:
      - ./linux-x64

build/osx-x64:
  stage: build
  image: microsoft/dotnet:latest
  only:
    - master
  except:
    - tags
  before_script:
    - ./ci-cd/upgrade-to-4.7.2.sh
  script:
    - dotnet restore
    - dotnet tool install --global dotnet-warp
    - cd ./kOS.Cli
    - dotnet-warp -r osx-x64 -o ../osx-x64/ksc
  artifacts:
    paths:
      - ./osx-x64

##############################################################
# Running unit tests.
##############################################################
test/unit-testing:
  stage: test
  image: microsoft/dotnet:latest
  except:
    - tags
  before_script:
    - ./ci-cd/upgrade-to-4.7.2.sh
  script:
    - dotnet test

##############################################################
# Deployment.
##############################################################
# deploy/nuget:
#   stage: deploy
#   image: microsoft/dotnet:latest
#   only:
#     - master
#   except:
#     - tags
#   script:
#     dotnet nuget push ./package/*.nupkg -k $NUGET_API_KEY -s nuget.org