##############################################################
# Variables.
##############################################################
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULES: init

##############################################################
# Build that shit.
##############################################################
build/debug:
  stage: build
  image: microsoft/dotnet:latest
  only:
    - develop
  except:
    - tags
  before_script:
    - bash ./gen-kos-safe-core.sh
  script:
    - dotnet restore
    - dotnet build

build/win-x64:
  stage: build
  image: microsoft/dotnet:latest
  only:
    - master
  except:
    - tags
  before_script:
    - bash ./gen-kos-safe-core.sh
  script:
    - dotnet publish -r win-x64 -c Release -o ./win-x64 -verbosity:diag
  artifacts:
    paths:
      - ./win-x64

build/win-x86:
  stage: build
  image: microsoft/dotnet:latest
  only:
    - master
  except:
    - tags
  before_script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - bash ./gen-kos-safe-core.sh
  script:
    - dotnet publish -r win-x86 -c Release -o ./win-x86 -verbosity:diag
  artifacts:
    paths:
      - ./win-x86

build/linux-x64:
  stage: build
  image: microsoft/dotnet:latest
  only:
    - master
  except:
    - tags
  before_script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - bash ./gen-kos-safe-core.sh
  script:
    - dotnet publish -r linux-x64 -c Release -o ./linux-x64 -verbosity:diag
  artifacts:
    paths:
      - ./linux-x64


build/osx-x64:
  stage: build
  image: microsoft/dotnet:latest
  only:
    - master
  except:
    - tags
  before_script:
    - export PATH="$PATH:/root/.dotnet/tools"
    - bash ./gen-kos-safe-core.sh
  script:
    - dotnet publish -r osx-x64 -c Release -o ./osx-x64 -verbosity:diag
  artifacts:
    paths:
      - ./osx-x64

##############################################################
# Running unit tests.
##############################################################
test/unit-testing:
  stage: test
  image: microsoft/dotnet:latest
  except:
    - tags
  before_script:
    - bash ./gen-kos-safe-core.sh
  script:
    - dotnet test

##############################################################
# Deployment.
##############################################################
# deploy/nuget:
#   stage: deploy
#   image: microsoft/dotnet:latest
#   only:
#     - master
#   except:
#     - tags
#   script:
#     dotnet nuget push ./package/*.nupkg -k $NUGET_API_KEY -s nuget.org